### ISSUE TITLE
Retrieve a player position based on the database

### ISSUE THREAD

**Issue by nwmqpa** [nwmqpa/Forge-Reverse-Proxy#4]
- [x] Make query on the API
- [x] Make call to the API in the proxy
- [x] Parse the position of the player

**Comment by Afourcat** [comment]
## Database
Where is the database, is it the minecraft server database ? Is it our database ?
If it's our, have you thinked about on ORM.
If not, how should I request these datas and have you some doc that can help me to understand this issue ?
## Position
Where should I store the position of the player? Should I create a struct for this purpose or should I create a Player struct for future use ? In this case can you define it more clearly ?

**Comment by nwmqpa** [comment]
The database isn't ready for you to make this request, however, it is already [accesible](https://api.utopia-server.com). It's a GraphQL endpoint, so it's fully schematized.
On the backend side of the API, there is already an ORM (Django) that is accesed throught Graphene, a GraphQL server written in python.
You should be able to get the schema from the endpoint.

For the position, it should contains 4 elements, x, y, z, and furthermore, the player dimension (each dimension is assigned a server)

The player structure seems to be a good start, and will lead the way to fake player soon.

**Comment by Afourcat** [comment]
Done with [#7](https://github.com/UtopiaServer/Forge-Reverse-Proxy/pull/7)
